export default {

  CURRENT_USER_RECEIVED: 'CURRENT_USER_RECEIVED',

  BOOKMARK_CREATED: 'BOOKMARK_CREATED',
  BOOKMARKS_RECEIVED: 'BOOKMARKS_RECEIVED',
  
  PROFILE_CREATED: 'PROFILE_CREATED',
  PROFILES_RECEIVED: 'PROFILES_RECEIVED',
  PROFILE_SELECTED: 'PROFILE_SELECTED',


}
